# Generated by Django 2.2.13 on 2020-06-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200630_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='api.Organization'),
        ),
    ]
